/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 public/assets/PlaceholderRoom/living_room_threejs.glb -o features/PlaceholderRoom/components/LivingRoomModel.tsx -t 
*/

import * as THREE from "three";
import React, { Suspense, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import Lamp from "./Lamp";
import Surroundings from "./Surroundings";
import Record from "./Record";
import { SONG } from "../types";
import Player from "./Player";
import ContactBook from "./ContactBook";
import Monitor from "./Monitor";
import Walls from "./Walls";
import useStore from "../store/useStore";
import PhotoFrame from "./PhotoFrame";

type GLTFResult = GLTF & {
	nodes: {
		Room_1: THREE.Mesh;
		Room_2: THREE.Mesh;
		BackWall: THREE.Mesh;
		RightWall: THREE.Mesh;
		Roof: THREE.Mesh;
		Window: THREE.Mesh;
		WindowFrame: THREE.Mesh;
		Table_1: THREE.Mesh;
		Table_2: THREE.Mesh;
		Shalves: THREE.Mesh;
		StereoTable: THREE.Mesh;
		Sofa_1: THREE.Mesh;
		Sofa_2: THREE.Mesh;
		Player_1: THREE.Mesh;
		Player_2: THREE.Mesh;
		PlayerKnobPower: THREE.Mesh;
		PlayerKnobVolume: THREE.Mesh;
		PlayerNeedle: THREE.Mesh;
		Record_1: THREE.Mesh;
		Record_2: THREE.Mesh;
		Speakers: THREE.Mesh;
		Record005: THREE.Mesh;
		Vinyl005_1: THREE.Mesh;
		Vinyl005_2: THREE.Mesh;
		Chair_1: THREE.Mesh;
		Chair_2: THREE.Mesh;
		Monitor: THREE.Mesh;
		Display: THREE.Mesh;
		DisplayActive: THREE.Mesh;
		Plant: THREE.Mesh;
		Tree_1: THREE.Mesh;
		Tree_2: THREE.Mesh;
		Vase: THREE.Mesh;
		CoffeTable_1: THREE.Mesh;
		CoffeTable_2: THREE.Mesh;
		CoffeTable_3: THREE.Mesh;
		Book0_1: THREE.Mesh;
		Book0_2: THREE.Mesh;
		Coffee: THREE.Mesh;
		CoffeeLiquid: THREE.Mesh;
		Frame: THREE.Mesh;
		FrameDisplay: THREE.Mesh;
		Keyboard: THREE.Mesh;
		KeyboardKeys: THREE.Mesh;
		Lamp_1: THREE.Mesh;
		Lamp_2: THREE.Mesh;
		LampEmission: THREE.Mesh;
		Mouse: THREE.Mesh;
		Painting: THREE.Mesh;
		Record001: THREE.Mesh;
		Vinyl001_1: THREE.Mesh;
		Vinyl001_2: THREE.Mesh;
		Record002: THREE.Mesh;
		Vinyl002_1: THREE.Mesh;
		Vinyl002_2: THREE.Mesh;
		Record003: THREE.Mesh;
		Vinyl003_1: THREE.Mesh;
		Vinyl003_2: THREE.Mesh;
		Record004: THREE.Mesh;
		Vinyl004_1: THREE.Mesh;
		Vinyl004_2: THREE.Mesh;
		Book0001_1: THREE.Mesh;
		Book0001_2: THREE.Mesh;
		Book0002_1: THREE.Mesh;
		Book0002_2: THREE.Mesh;
		Book0003_1: THREE.Mesh;
		Book0003_2: THREE.Mesh;
		Book0012_1: THREE.Mesh;
		Book0012_2: THREE.Mesh;
		Book0013_1: THREE.Mesh;
		Book0013_2: THREE.Mesh;
		Book0014: THREE.Mesh;
		Book0014_1: THREE.Mesh;
		Book0015: THREE.Mesh;
		Book0015_1: THREE.Mesh;
		Book0016: THREE.Mesh;
		Book0016_1: THREE.Mesh;
		Book0017: THREE.Mesh;
		Book0017_1: THREE.Mesh;
		Book0018: THREE.Mesh;
		Book0018_1: THREE.Mesh;
		Book0019: THREE.Mesh;
		Book0019_1: THREE.Mesh;
		Book0020: THREE.Mesh;
		Book0020_1: THREE.Mesh;
		Book0021: THREE.Mesh;
		Book0021_1: THREE.Mesh;
		ContactBook: THREE.Mesh;
		BookPaper: THREE.Mesh;
		Email_1: THREE.Mesh;
		Email_2: THREE.Mesh;
		LeftTopPage: THREE.Mesh;
		LinkedIn_1: THREE.Mesh;
		LinkedIn_2: THREE.Mesh;
		Pencil_1: THREE.Mesh;
		Pencil_2: THREE.Mesh;
		X_1: THREE.Mesh;
		X_2: THREE.Mesh;
	};
	materials: {
		White: THREE.MeshStandardMaterial;
		Floor: THREE.MeshStandardMaterial;
		Windows: THREE.MeshStandardMaterial;
		Wood: THREE.MeshStandardMaterial;
		Steel: THREE.MeshStandardMaterial;
		WoodDark: THREE.MeshStandardMaterial;
		Sofa: THREE.MeshStandardMaterial;
		Black: THREE.MeshStandardMaterial;
		["Black.001"]: THREE.MeshStandardMaterial;
		SunnyDaydreams: THREE.MeshStandardMaterial;
		["Black.002"]: THREE.MeshStandardMaterial;
		["White.001"]: THREE.MeshStandardMaterial;
		Plant: THREE.MeshStandardMaterial;
		Leafs: THREE.MeshStandardMaterial;
		Dirt: THREE.MeshStandardMaterial;
		Stamp: THREE.MeshStandardMaterial;
		["Book.001"]: THREE.MeshStandardMaterial;
		["colourful-painted-surface"]: THREE.MeshStandardMaterial;
		WEARETHEGOODLiveintheMoment: THREE.MeshStandardMaterial;
		SOURWAHBreakingThrough: THREE.MeshStandardMaterial;
		NovembersLOW: THREE.MeshStandardMaterial;
		ShookUp: THREE.MeshStandardMaterial;
		["Book.002"]: THREE.MeshStandardMaterial;
		["Book.003"]: THREE.MeshStandardMaterial;
		["Book.004"]: THREE.MeshStandardMaterial;
		["Book.005"]: THREE.MeshStandardMaterial;
		["Book.006"]: THREE.MeshStandardMaterial;
		["Book.007"]: THREE.MeshStandardMaterial;
		["Book.008"]: THREE.MeshStandardMaterial;
		["Book.009"]: THREE.MeshStandardMaterial;
		["Book.010"]: THREE.MeshStandardMaterial;
		["Book.011"]: THREE.MeshStandardMaterial;
		["Book.014"]: THREE.MeshStandardMaterial;
		["Book.012"]: THREE.MeshStandardMaterial;
		["Book.013"]: THREE.MeshStandardMaterial;
		SVGMat: THREE.MeshStandardMaterial;
		BookMessage: THREE.MeshStandardMaterial;
	};
};

type ContextType = Record<
	string,
	React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function LivingRoomModel(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF(
		"/assets/PlaceholderRoom/living_room_threejs.glb"
	) as GLTFResult;

	const setIsReady = useStore((state) => state.setIsReady);

	useEffect(() => {
		setIsReady(true);
	}, [setIsReady]);

	return (
		<group
			{...props}
			dispose={null}
		>
			<mesh geometry={nodes.Window.geometry}>
				<mesh
					geometry={nodes.WindowFrame.geometry}
					material={materials.Wood}
					position={[0, 0, -0.163]}
					castShadow
				/>

				<Suspense>
					<Surroundings />
				</Suspense>
			</mesh>

			<group position={[0, 0, -3.108]}>
				<mesh
					geometry={nodes.Table_1.geometry}
					material={materials.Wood}
					receiveShadow
					castShadow
				/>
				<mesh
					geometry={nodes.Table_2.geometry}
					material={materials.Steel}
					receiveShadow
				/>
			</group>
			<mesh
				geometry={nodes.Shalves.geometry}
				material={materials.Wood}
				position={[-3.999, 0, -1.891]}
				receiveShadow
				castShadow
			/>
			<mesh
				geometry={nodes.StereoTable.geometry}
				material={materials.WoodDark}
				position={[3.343, 0, 1.031]}
				receiveShadow
				castShadow
			/>
			<group position={[-2.948, 0.001, 1.025]}>
				<mesh
					geometry={nodes.Sofa_1.geometry}
					material={materials.Sofa}
					receiveShadow
					castShadow
				/>
				<mesh
					geometry={nodes.Sofa_2.geometry}
					material={materials.Steel}
					receiveShadow
				/>
			</group>

			<Player
				position={[3.343, 0.561, 0.978]}
				nodes={nodes}
				materials={materials}
			/>

			<mesh
				geometry={nodes.Speakers.geometry}
				material={materials["Black.001"]}
				position={[3.343, 0, 1.031]}
				castShadow
				receiveShadow
			/>

			<group position={[0, 0, -1.327]}>
				<mesh
					geometry={nodes.Chair_1.geometry}
					material={materials.Sofa}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes.Chair_2.geometry}
					material={materials.Steel}
					castShadow
					receiveShadow
				/>
			</group>

			<Monitor
				position={[0.018, 1.783, -3.073]}
				nodes={nodes}
				materials={materials}
			/>

			<mesh
				geometry={nodes.Plant.geometry}
				material={materials["White.001"]}
				position={[3.13, 0, -2.664]}
				rotation={[0, 1.255, 0]}
				castShadow
				receiveShadow
			>
				<mesh
					geometry={nodes.Vase.geometry}
					material={materials.Dirt}
					receiveShadow
				/>
				<mesh
					geometry={nodes.Tree_1.geometry}
					material={materials.Plant}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes.Tree_2.geometry}
					material={materials.Leafs}
					castShadow
					receiveShadow
				/>
			</mesh>
			<group position={[-0.05, 0, 1.786]}>
				<mesh
					geometry={nodes.CoffeTable_1.geometry}
					material={materials.WoodDark}
					receiveShadow
				/>
				<mesh
					geometry={nodes.CoffeTable_2.geometry}
					material={materials.Stamp}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes.CoffeTable_3.geometry}
					material={materials.Steel}
					castShadow
					receiveShadow
				/>
			</group>
			<group
				position={[-3.75, 3.018, -0.536]}
				rotation={[-0.302, 1.571, 0]}
			>
				<mesh
					geometry={nodes.Book0_1.geometry}
					material={materials["Book.001"]}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes.Book0_2.geometry}
					material={materials.White}
				/>
			</group>
			<mesh
				geometry={nodes.Coffee.geometry}
				material={materials["White.001"]}
				position={[-1.033, 1.782, -2.63]}
				rotation={[0, 0.576, 0]}
				castShadow
				receiveShadow
			>
				<mesh
					geometry={nodes.CoffeeLiquid.geometry}
					material={materials["Black.002"]}
				/>
			</mesh>

			<mesh
				geometry={nodes.Keyboard.geometry}
				material={materials.Steel}
				position={[-0.008, 1.782, -2.679]}
				rotation={[0.001, 0, 0]}
				castShadow
				receiveShadow
			>
				<mesh
					geometry={nodes.KeyboardKeys.geometry}
					material={materials["Black.001"]}
					rotation={[0.084, 0, 0]}
					receiveShadow
				/>
			</mesh>

			<Lamp
				nodes={nodes}
				materials={materials}
			/>

			<mesh
				geometry={nodes.Mouse.geometry}
				material={materials["White.001"]}
				position={[0.904, 1.782, -2.782]}
				rotation={[0.001, 0, 0]}
				receiveShadow
			/>
			<mesh
				geometry={nodes.Painting.geometry}
				material={materials["colourful-painted-surface"]}
				position={[-4, 3.287, 1.552]}
				rotation={[0, 0, -Math.PI / 2]}
				castShadow
				receiveShadow
			/>
			<Record
				recordId={SONG.FIRST}
				position={[3.344, 0.899, -0.761]}
				rotation={[0.921, 0, 0]}
				nodes={{
					Cover: nodes.Record005,
					VinylBlack: nodes.Vinyl005_1,
					VinylWhite: nodes.Vinyl005_2,
				}}
				materials={{
					Cover: materials.SunnyDaydreams,
					VinylBlack: materials.Black,
					VinylWhite: materials.White,
				}}
			/>

			<Record
				recordId={SONG.SECOND}
				position={[3.28, 0.914, -0.826]}
				rotation={[1.002, 0, 0]}
				nodes={{
					Cover: nodes.Record002,
					VinylBlack: nodes.Vinyl002_1,
					VinylWhite: nodes.Vinyl002_2,
				}}
				materials={{
					Cover: materials.SOURWAHBreakingThrough,
					VinylBlack: materials.Black,
					VinylWhite: materials.White,
				}}
			/>

			<Record
				recordId={SONG.THIRD}
				position={[3.344, 0.928, -0.883]}
				rotation={[1.082, 0, 0]}
				nodes={{
					Cover: nodes.Record003,
					VinylBlack: nodes.Vinyl003_1,
					VinylWhite: nodes.Vinyl003_2,
				}}
				materials={{
					Cover: materials.NovembersLOW,
					VinylBlack: materials.Black,
					VinylWhite: materials.White,
				}}
			/>

			<Record
				recordId={SONG.FORTH}
				position={[3.404, 0.941, -0.927]}
				rotation={[1.142, 0, 0]}
				nodes={{
					Cover: nodes.Record001,
					VinylBlack: nodes.Vinyl001_1,
					VinylWhite: nodes.Vinyl001_2,
				}}
				materials={{
					Cover: materials.WEARETHEGOODLiveintheMoment,
					VinylBlack: materials.Black,
					VinylWhite: materials.White,
				}}
			/>

			<Record
				recordId={SONG.FIFTH}
				position={[3.328, 0.95, -0.971]}
				rotation={[1.205, 0, 0]}
				nodes={{
					Cover: nodes.Record004,
					VinylBlack: nodes.Vinyl004_1,
					VinylWhite: nodes.Vinyl004_2,
				}}
				materials={{
					Cover: materials.ShookUp,
					VinylBlack: materials.Black,
					VinylWhite: materials.White,
				}}
			/>

			<group
				position={[-3.765, 2.997, -0.743]}
				rotation={[0, Math.PI / 2, 0]}
			>
				<mesh
					geometry={nodes.Book0001_1.geometry}
					material={materials["Book.002"]}
					castShadow
				/>
				<mesh
					geometry={nodes.Book0001_2.geometry}
					material={materials.White}
				/>
			</group>
			<group
				position={[-3.75, 2.997, -0.801]}
				rotation={[0, Math.PI / 2, 0]}
			>
				<mesh
					geometry={nodes.Book0002_1.geometry}
					material={materials["Book.003"]}
					castShadow
				/>
				<mesh
					geometry={nodes.Book0002_2.geometry}
					material={materials.White}
				/>
			</group>
			<group
				position={[-3.762, 2.997, -0.864]}
				rotation={[0, Math.PI / 2, 0]}
			>
				<mesh
					geometry={nodes.Book0003_1.geometry}
					material={materials["Book.004"]}
					castShadow
				/>
				<mesh
					geometry={nodes.Book0003_2.geometry}
					material={materials.White}
				/>
			</group>
			<group
				position={[-3.75, 2.998, -0.94]}
				rotation={[0, Math.PI / 2, 0]}
			>
				<mesh
					geometry={nodes.Book0012_1.geometry}
					material={materials["Book.005"]}
					castShadow
				/>
				<mesh
					geometry={nodes.Book0012_2.geometry}
					material={materials.White}
				/>
			</group>
			<group
				position={[-3.679, 2.998, -1.017]}
				rotation={[0, Math.PI / 2, 0]}
			>
				<mesh
					geometry={nodes.Book0013_1.geometry}
					material={materials["Book.006"]}
					castShadow
				/>
				<mesh
					geometry={nodes.Book0013_2.geometry}
					material={materials.White}
				/>
			</group>
			<group
				position={[-3.75, 2.998, -1.062]}
				rotation={[0, Math.PI / 2, 0]}
			>
				<mesh
					geometry={nodes.Book0014.geometry}
					material={materials["Book.007"]}
					castShadow
				/>
				<mesh
					geometry={nodes.Book0014_1.geometry}
					material={materials.White}
				/>
			</group>
			<group
				position={[-3.75, 2.998, -1.131]}
				rotation={[0, Math.PI / 2, 0]}
			>
				<mesh
					geometry={nodes.Book0015.geometry}
					material={materials["Book.008"]}
					castShadow
				/>
				<mesh
					geometry={nodes.Book0015_1.geometry}
					material={materials.White}
				/>
			</group>
			<group
				position={[-3.75, 2.998, -1.174]}
				rotation={[0, Math.PI / 2, 0]}
			>
				<mesh
					geometry={nodes.Book0016.geometry}
					material={materials["Book.009"]}
					castShadow
				/>
				<mesh
					geometry={nodes.Book0016_1.geometry}
					material={materials.White}
				/>
			</group>
			<group
				position={[-3.75, 2.998, -1.239]}
				rotation={[0, Math.PI / 2, 0]}
			>
				<mesh
					geometry={nodes.Book0017.geometry}
					material={materials["Book.010"]}
					castShadow
				/>
				<mesh
					geometry={nodes.Book0017_1.geometry}
					material={materials.White}
				/>
			</group>
			<group
				position={[-3.75, 2.998, -1.303]}
				rotation={[0, Math.PI / 2, 0]}
			>
				<mesh
					geometry={nodes.Book0018.geometry}
					material={materials["Book.011"]}
					castShadow
				/>
				<mesh
					geometry={nodes.Book0018_1.geometry}
					material={materials.White}
				/>
			</group>
			<group
				position={[-3.75, 2.998, -1.522]}
				rotation={[0, Math.PI / 2, 0]}
			>
				<mesh
					geometry={nodes.Book0019.geometry}
					material={materials["Book.014"]}
				/>
				<mesh
					geometry={nodes.Book0019_1.geometry}
					material={materials.White}
				/>
			</group>
			<group
				position={[-3.75, 2.998, -1.409]}
				rotation={[0, Math.PI / 2, 0]}
			>
				<mesh
					geometry={nodes.Book0020.geometry}
					material={materials["Book.012"]}
					castShadow
				/>
				<mesh
					geometry={nodes.Book0020_1.geometry}
					material={materials.White}
				/>
			</group>
			<group
				position={[-3.75, 2.998, -1.458]}
				rotation={[0, Math.PI / 2, 0]}
			>
				<mesh
					geometry={nodes.Book0021.geometry}
					material={materials["Book.013"]}
					castShadow
				/>
				<mesh
					geometry={nodes.Book0021_1.geometry}
					material={materials.White}
				/>
			</group>

			<ContactBook
				position={[1.059, 1.782, -3.401]}
				rotation={[0, 0.427, 0]}
				nodes={nodes}
				materials={materials}
			/>

			<mesh
				geometry={nodes.Room_1.geometry}
				material={materials.White}
				castShadow
				receiveShadow
			/>
			<mesh
				geometry={nodes.Room_2.geometry}
				material={materials.Floor}
				receiveShadow
			/>

			<PhotoFrame
				position={[-3.581, 3.607, -2.343]}
				rotation={[0, -0.269, 0]}
				nodes={nodes}
				materials={materials}
			/>

			<Walls
				nodes={nodes}
				materials={materials}
			/>
		</group>
	);
}
